### ISSUE TITLE
Updatin to Alfred 4

### ISSUE THREAD

**Issue by skoskie** [pochemuto/alfred-help-workflow#10]
For anyone else who comes here looking for an update to make this workflow compatible with Alfred 4, you'll be happy to know it already is. You just need to make one quick and easy change to the workflow you already have installed. 

## Just Three Easy Steps!

1. Open Alfred preferences to the Workflows tab. 

2. Open the configuration for the "Run Script" component. Like so...
    
    <img width="855" alt="Screenshot 2019-06-19 13 08 46" src="https://user-images.githubusercontent.com/495511/59793695-6511ef00-9294-11e9-8774-8dfa4b13c194.png">

3. Change the version of Alfred from 3 to 4 as you see in the screenshot.

    <img width="784" alt="Screenshot 2019-06-19 13 10 22" src="https://user-images.githubusercontent.com/495511/59793673-59262d00-9294-11e9-9cba-1ed38ee29ae2.png">

That's it! it should now begin working again.

**Comment by pochemuto** [comment]
Thank you for your fix! Please, check out new version with alfred 4 support. https://github.com/pochemuto/alfred-help-workflow/releases/tag/v1.5.0
