### ISSUE TITLE
Why workflow connects to the Internet?

### ISSUE THREAD

**Issue by aik099** [pochemuto/alfred-help-workflow#11]
When I started the workflow for the first time it attempted to connect to the Internet. Based on workflow description is should be operating without internet at all.

**Comment by pochemuto** [comment]
Workflow is based on alfred-workflow library from deanishe. https://github.com/deanishe/alfred-workflow#features
It has feature to check updates. Periodically it fetches https://github.com/pochemuto/alfred-help-workflow/releases.

**Comment by aik099** [comment]
Wasn't aware of that. My only option would be blocking any attempts to contact GitHub from within Alfred then.

Thank you.

**Comment by pochemuto** [comment]
There is another option. Call:
```? workflow:noautoupdate``` to disable auto update
Call ```? workflow:autoupdate``` to enable back again
