### ISSUE TITLE
Update Dependency

### ISSUE THREAD

**Issue by eightygrit** [pochemuto/alfred-help-workflow#2]
Could you please update the [Alfred Workflow](https://github.com/deanishe/alfred-workflow) dependency in order to resolve a bug that makes your workflow unusable.

More information here: https://www.alfredapp.com/help/troubleshooting/incompatible-python-workflow-library/

**Comment by pochemuto** [comment]
Could you check updated version for few weeks? 

[alfred-keywords-help-1.1.alfredworkflow.zip](https://github.com/pochemuto/alfred-help-workflow/files/1998494/alfred-keywords-help-1.1.alfredworkflow.zip)

**Comment by pochemuto** [comment]
released in https://github.com/pochemuto/alfred-help-workflow/releases/tag/v1.1
